name: Docker

on:
  release:
    types:
    - created

env:
  IMAGE_NAME: sendinblue-email-provider

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Package maven jar
        run: mvn clean package -DskipTests -Djar.name=sendinblue

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .github/workflows/Dockerfile
          tags: intension/{{ sendinblue-email-provider }}:${GITHUB_REF##*/}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .github/workflows/Dockerfile
          tags: intension/{{ sendinblue-email-provider }}:latest
